version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: app
    volumes:
      - .:/var/www
    networks:
      - app-networks
    depends_on:
      - db
      - redis
  nginx:
    build: .docker/nginx
    container_name: nginx
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-networks
    depends_on:
      - app
  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-networks
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
